{"name": "Проверка ошибки при попытке авторизоваться с неверным паролем (password)", "status": "passed", "start": 1710083590291, "stop": 1710083590847, "uuid": "35b4e220-a774-4639-b7b9-ba8aae95158e", "historyId": "97ac677b0661cbb0f11f7b6f383d67d2", "testCaseId": "97ac677b0661cbb0f11f7b6f383d67d2", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_incorrect_password_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "CPR-2NBMZ33"}, {"name": "thread", "value": "22464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}